#!/bin/sh

set -e

if [ -d ndk-pkg-formula-repository-official-core ] ; then
    git -C ndk-pkg-formula-repository-official-core pull
else
    git clone --depth=1 https://github.com/leleliu008/ndk-pkg-formula-repository-official-core
fi

cd ndk-pkg-formula-repository-official-core/formula

unset PKGS

for f in *.yml
do
    unset PKGNAME
    unset PKGTYPE
    unset BSYSTEM
    unset DOBUILD

    PKGTYPE="$(sed -n '/^pkgtype:/p' "$f" | cut -c10-)"

    if [ -z "$PKGTYPE" ] ; then
        PKGNAME="${f%.yml}"

        case $PKGNAME in
            lib*) continue ;;
            *lib) continue ;;
            *-dev) continue ;;
            d8)   continue ;;
            calc) continue ;;
            fortune) continue ;;
               *)
    
                BSYSTEM="$(sed -n '/^bsystem:/p' "$f" | cut -c10-)"

                if [ -z "$BSYSTEM" ] ; then
                    DOBUILD="$(yq '.install | select(. != null)' "$f")"

                    if [ -n "$DOBUILD" ] ; then
                        for FirstWordOfLineInInstallActions in $(printf '%s\n' "$DOBUILD" | sed 's|^[[:space:]]*||' | cut -d ' ' -f1)
                        do
                            case "$FirstWordOfLineInInstallActions" in
                                go|gow) BSYSTEM=go ; break ;;
                            esac
                        done
                    fi
                fi

                if [ "$BSYSTEM" != go ] ; then
                    PKGTYPE=exe
                fi
        esac
    fi

    if [ "$PKGTYPE" = exe ] ; then
        PKGS="$PKGS
$PKGNAME"
    fi
done

list_size() {
    printf '%s\n' "$#"
}

PKGS_COUNT="$(list_size $PKGS)"

echo "PKGS_COUNT=$PKGS_COUNT"

cd -

cat > .github/workflows/publish.yml <<EOF
name: publish

on:
  workflow_dispatch

jobs:
EOF

unset ITEMS
unset NEEDS

I=0
J=0
K=0

for item in $PKGS
do
    if [ -z "$ITEMS" ] ; then
        ITEMS="$item"
    else
        ITEMS="$ITEMS, $item"
    fi

    K=$(($K + 1))

    J=$(($J + 1))

    echo "J=$J"
    echo "K=$K"

    if [ "$J" = 256 ] || [ "$K" = "$PKGS_COUNT" ] ; then
        J=0
        I=$(($I + 1))

        cat >> .github/workflows/publish.yml <<EOF

  build$I:
    strategy:
      fail-fast: false
      matrix:
        pkg: [$ITEMS]

    runs-on: ubuntu-latest

    container: ubuntu:24.04

    steps:
      - run: apt -y update
      - run: apt -y install curl

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/ndk-pkg
      - run: chmod a+x ndk-pkg

      - run: ./ndk-pkg about
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg update
      - run: ./ndk-pkg install android-35-arm64-v8a/\${{ matrix.pkg }} --static
      - run: ./ndk-pkg bundle  android-35-arm64-v8a/\${{ matrix.pkg }} .tar.xz --exclude include/ --exclude lib/

      - name: generate \${{ matrix.pkg }}.yml
        run: |
          set -ex

          PACKAGE_SUMMARY="\$(./ndk-pkg info-installed android-35-arm64-v8a/\${{ matrix.pkg }} summary)"
          PACKAGE_WEB_URL="\$(./ndk-pkg info-installed android-35-arm64-v8a/\${{ matrix.pkg }} web-url)"
          PACKAGE_VERSION="\$(./ndk-pkg info-installed android-35-arm64-v8a/\${{ matrix.pkg }} version)"

          PACKAGE_FILENAME="\$(ls *-android-aarch64.release.tar.xz)"
          PACKAGE_BIN_SHA="\$(sha256sum "\$PACKAGE_FILENAME" | cut -d ' ' -f1)"

          PACKAGE_BIN_URL="https://github.com/\${{ github.repository }}/releases/download/@TAGNAME@/\$PACKAGE_FILENAME"

          cat > \${{ matrix.pkg }}.yml <<EOF
          summary: \$PACKAGE_SUMMARY
          webpage: \$PACKAGE_WEB_URL
          version: \$PACKAGE_VERSION
          bin-url: \$PACKAGE_BIN_URL
          bin-sha: \$PACKAGE_BIN_SHA
          EOF

      - uses: actions/upload-artifact@v4
        with:
          name: \${{ matrix.pkg }}
          path: |
            ./*.tar.xz
            ./*.yml
EOF

        unset ITEMS

        if [ -z "$NEEDS" ] ; then
            NEEDS="build$I"
        else
            NEEDS="$NEEDS, build$I"
        fi
    fi
done

cat >> .github/workflows/publish.yml <<EOF

  publish:
    needs: [$NEEDS]

EOF

cat >> .github/workflows/publish.yml < foot
